```{r}
library(rgdal)
library(leaflet)
library(leaflet.extras)

library(dplyr)
library(readxl)
library(stringr)
library(rgdal)
```

```{r}
quakes.point <- readOGR("https://opendata.arcgis.com/datasets/e0abee7e4fa446ea8cfe618bca7e60e4_62.geojson")
hwinjury.lines <- readOGR("https://opendata.arcgis.com/datasets/a1fb5f1eb42a4e139cc8c89b468865a7_0.geojson")
demog.poly <- readOGR("https://opendata.arcgis.com/datasets/2f11013d1302419aac243d6e1c56568f_0.geojson")
#schooldist.poly <- readOGR("https://opendata.arcgis.com/datasets/07a10be1eb674ca99fd147474e1e0ca0_0.geojson")
```

#Points
```{r}
leaflet(quakes.point) %>%
  addProviderTiles("Esri.WorldImagery", group = "Base") %>%
  addProviderTiles("Esri.WorldTerrain", group = "Terrain") %>%
  addProviderTiles("OpenStreetMap.BlackAndWhite", group = "Black and White") %>%
  addLayersControl(
    baseGroups = c("Base", "Terrain", "Black and White"),
    options = layersControlOptions(collapsed = FALSE)) %>%
  addMarkers(  
    clusterOptions = markerClusterOptions()
)
  
#addMarkers(~longitude, ~latitude, popup = ~as.character(Name), label = ~as.character(Name))
#label vs popup; if you have labels, don't need popup and vice versa
```

#Lines
```{r}
leaflet(data = hwinjury.lines) %>%
  addProviderTiles("OpenStreetMap.BlackAndWhite") %>%
  addPolylines(color = "red")
```

#Polygons

```{r}
bins <- stats::quantile(demog.poly$hislat)
pal <- colorBin(c("#f7f7f7","#cccccc","#969696","#636363","#252525"), domain = demog.poly$hislat, bins = bins)

leaflet(demog.poly) %>%
  addProviderTiles("OpenStreetMap.Mapnik") %>%
  addPolygons(
    fillColor = ~pal(hislat),
    weight = 2,
    fillOpacity = .8,
    color ="white"
  ) %>%
  addLegend(position = "topright" , pal = pal, values = demog.poly$hislat, title = "Hispanic/Latinos by County", labFormat = labelFormat(digits = 0))

#have to do labFormat = labelFormat because that's going out of order in the addLegend function
#If I want to see percents in my legend, I have to calculate a column of percents and then add "%" in the suffix argument for the addLegend function so it reads __%
```


#Polygons (ignore, but I want to keep this for myself)
```{r}
# leaflet(schooldist.poly) %>%
#   addProviderTiles("OpenStreetMap.Mapnik") %>%
#   addPolygons()
```
